services:
  tverse_server_db:
    image: postgres:16.1-alpine3.19
    container_name: tverse_server_db
    expose:
      - 5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=termverse
      - POSTGRES_PASSWORD=local
    command: -p 5433

  termverse_server:
    container_name: termverse_server
    build:
      context: ./TermverseWeb
      dockerfile: backend.Dockerfile
    ports:
      - 8081:8080
    environment:
      DATASOURCE_URL: jdbc:postgresql://tverse_server_db:5433/termverse
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: local

      KEYCLOAK_CLIENT_ID: termverse_app
      KEYCLOAK_SECRET: jikvp5fJQE7yOl6723o2ewb9PYIXDDbK
      JWT_SECRET: askfj-dskfSJ23-SSADSXX_d34032et3453-XX44S

      APP_SECRET: local

  termverse_client:
    container_name: termverse_client
    build:
      context: ./TermveseSceleton/termverse-sceleton
      dockerfile: client.Dockerfile
    ports:
      - 3000:3000
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXT_PUBLIC_API_URL: http://localhost:3000/api/auth
      NEXTAUTH_SECRET: 232390jakpffnldhi3nvPAnrbuidda0334h04-3234324
      JWT_SECRET: askfj-dskfSJ23-SSADSXX_d34032et3453-XX44S
      KEYCLOAK_CLIENT_ID: termverse_app
      KEYCLOAK_SECRET: jikvp5fJQE7yOl6723o2ewb9PYIXDDbK
      CHOKIDAR_USEPOLLING: true

  tverse_keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: tverse_keycloak
    volumes:
      - ./imports:/tmp/imports
    ports:
      - 8180:8180
      - 8443:8443
    environment:
      JWT_SECRET: askfj-dskfSJ23-SSADSXX_d34032et3453-XX44S

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://tverse_keycloak_db:5434/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      keycloak.url: http://keycloak:8180
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180
      HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY: none
      KC_PROXY_ADDRESS_FORWARDING: true

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: 00root11
    command: [start-dev, --http-port=8180, --import-realm]

    restart: always
    depends_on:
      - tverse_keycloak_db

  tverse_keycloak_db:
    image: postgres:16.1-alpine3.19
    container_name: tverse_keycloak_db
    expose:
      - 5434
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=password
    command: -p 5434